import type { TeamMember, Task } from './types';

export const teamMembers: TeamMember[] = [
  { id: '1', name: 'Alice Johnson', avatarUrl: 'https://placehold.co/40x40.png', skills: ['Frontend', 'UI/UX'], availability: '40 horas/semana', currentWorkload: 20 },
  { id: '2', name: 'Bob Williams', avatarUrl: 'https://placehold.co/40x40.png', skills: ['Backend', 'Banco de Dados'], availability: '40 horas/semana', currentWorkload: 30 },
  { id: '3', name: 'Charlie Brown', avatarUrl: 'https://placehold.co/40x40.png', skills: ['DevOps', 'CI/CD'], availability: '30 horas/semana', currentWorkload: 15 },
  { id: '4', name: 'Diana Prince', avatarUrl: 'https://placehold.co/40x40.png', skills: ['QA', 'Testes'], availability: '40 horas/semana', currentWorkload: 25 },
];

export const tasks: Task[] = [
  {
    id: 'task-1',
    title: 'Desenhar mockups da página inicial',
    description: 'Criar mockups de alta fidelidade no Figma para a nova página inicial.',
    status: 'todo',
    priority: 'high',
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: teamMembers[0],
  },
  {
    id: 'task-2',
    title: 'Desenvolver API de autenticação de usuário',
    description: 'Configurar endpoints para registro, login e logout de usuários.',
    status: 'inprogress',
    priority: 'high',
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: teamMembers[1],
  },
  {
    id: 'task-3',
    title: 'Configurar pipeline de CI/CD',
    description: 'Configurar GitHub Actions para testes e implantação automatizados.',
    status: 'inprogress',
    priority: 'medium',
    deadline: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: teamMembers[2],
  },
  {
    id: 'task-4',
    title: 'Escrever testes E2E para fluxo de login',
    description: 'Usar o Cypress para escrever testes de ponta a ponta para o fluxo de autenticação do usuário.',
    status: 'todo',
    priority: 'medium',
    deadline: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: teamMembers[3],
  },
  {
    id: 'task-5',
    title: 'Refatorar esquema do banco de dados',
    description: 'Otimizar o esquema do banco de dados para melhor desempenho.',
    status: 'done',
    priority: 'low',
    deadline: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: teamMembers[1],
  },
  {
    id: 'task-6',
    title: 'Implementar recurso de redefinição de senha',
    status: 'todo',
    priority: 'high',
    deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-7',
    title: 'Atualizar documentação da API',
    status: 'done',
    priority: 'low',
    deadline: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: teamMembers[0],
  },
  {
    id: 'task-8',
    title: 'Integrar novo estagiário de marketing',
    description: 'Preparar materiais de integração e agendar reuniões de apresentação.',
    status: 'done',
    priority: 'medium',
    deadline: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    assignee: teamMembers[0],
  },
];
